/** DO NOT EDIT, this file is generated by metagen.py
 */

#include "dyn_update.h"

namespace MetaData
{
    {% for clazz in classes -%}
    Reflection::ClassMetaData META_DATA_{{clazz.name}} = {
        "{{clazz.fqn()}}",
        "{{clazz.compat}}",
        {
            {% for field in clazz.fields -%}
                {% if not field.first %},{%endif %} 
                Reflection::FieldMetaData{ "{{field.name}}" }
            {% endfor %}
        }
    };
    {% endfor %}
}

